; Add RPC サンプル (server)
; 事前に環境変数 ROBOSTEP_LIBS_CPP に robostep-libs-cpp のパスを設定すること。
;   例: ROBOSTEP_LIBS_CPP=C:/path/to/nhk-r1/libs/robostep-libs-cpp

[env:nucleo_f446re]
platform = ststm32
board = nucleo_f446re
framework = mbed
upload_protocol = stlink
lib_deps =
    symlink://../..
build_flags =
    -std=c++17
    -I../common
    -I${sysenv.ROBOSTEP_LIBS_CPP}/utils/mbed/can-api
